### PR TITLE
Fix source distribution.

### PR DESCRIPTION
**Pull request by hodgestar**
Addresses #10.

### CODE REVIEW

**Comment by hodgestar** [comment]
The problem occurs on readthedocs as follows:
```
Downloading https://pypi.python.org/packages/source/p/python-smpp/python-smpp-0.1.7.tar.gz#md5=3cd698ccad892c6ea8431089d851cf15
Processing python-smpp-0.1.7.tar.gz
Writing /tmp/easy_install-UaUCde/python-smpp-0.1.7/setup.cfg
Running python-smpp-0.1.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-UaUCde/python-smpp-0.1.7/egg-dist-tmp-4qyuPW
warning: no previously-included files found matching 'test/*'
warning: no previously-included files found matching 'tests.py'
zip_safe flag not set; analyzing archive contents...
No eggs found in /tmp/easy_install-UaUCde/python-smpp-0.1.7/egg-dist-tmp-4qyuPW (setup script problem?)
```
But I'm not 100% what is wrong yet.

The changes so far are just general clean-ups.

**Comment by hodgestar** [comment]
I can reproduce this locally by running `python setup.py install --force` for https://github.com/praekelt/junebug.

**Comment by jerith** [comment]
After some experimentation, I've determined that the problem is the `exclude *.egg-info/*` in `MANIFEST.in`. The contents of the `.egg-info` dir gets added to the egg that `easy_install` builds during installation. If the `PKG-INFO` file is missing (which happens if the egg is built from a source package without rebuilding the egg-info, as during an `easy_install` installation), the egg doesn't look like a package and is therefore ignored when `easy_install` tries to find the thing it just built to install it.

Yay setuptools.

**Comment by jerith** [comment]
:+1: to the commits prior to mine, although only the `exclude *.egg-info/*` change is actually necessary for `easy_install` to work.

**Comment by hodgestar** [comment]
Thanks for chasing down the `.egg-info` issue.

:+1: (and merging)

**Pull request merged**
