### PR TITLE
The validity period for a submit_sm is variable length

### PR DESCRIPTION
**Pull request by SimonStJG**
See SMPP v3.4 specification section 4.4.1.

### CODE REVIEW

**Comment by hodgestar** [comment]
Thanks! Is there any chance you could add a test that demonstrates the issue?

**Comment by SimonStJG** [comment]
Sure.  I'm a bit busy today, but should be able to get you one tomorrow.

**Comment by hodgestar** [comment]
Woot!

**Comment by SimonStJG** [comment]
I've added a test.

**Comment by hodgestar** [comment]
Thanks! Will merge once Travis build is done.

:+1:

**Comment by hodgestar** [comment]
@SimonStJG released in version 0.1.9 (https://pypi.python.org/pypi/python-smpp/0.1.9). Thanks!

**Pull request merged**
